<?php
// vim: set ts=2 sw=2 sts=2 et:
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with block package in the file LICENSE.txt.
 * It is also available through the world-wide-web at block URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @author     Qualiteam Software <info@x-cart.com>
 * @category   CDev
 * @package    CDev_XPaymentsConnector
 * @copyright  (c) 2010-present Qualiteam software Ltd <info@x-cart.com>. All rights reserved
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
/**
 * @see CDev\XPaymentsConnector\Block\Adminhtml\Settings\Tab\PaymentMethods
 */
?>

<form action="<?php echo $block->escapeUrl($block->getUrl('xpc/settings/paymentmethods')); ?>" method="post" name="update_form" id="payment-methods-form">
  <?php echo $block->getBlockHtml('formkey'); ?>
  <input type="hidden" name="store" value="<?php echo $block->getCurrentStoreId(); ?>" />
  <input type="hidden" name="mode" value="update" id="payment-method-form-mode" />

  <div class="fieldset-wrapper-title">
    <strong class="title"><?php echo $block->escapeHtml(__('Payment configurations')); ?></strong>
  </div>

  <?php echo $block->getChildHtml('xpc_payment_configuration_listing'); ?>

  <div class="fieldset-wrapper-title">
    <strong class="title"><?php echo $block->escapeHtml(__('Payment method')); ?></strong>
  </div>

  <div class="fieldset-wrapper">
    <fieldset class="admin__fieldset">

      <?php echo $block->getChildHtml('xpc_settings_payment_method_enabled'); ?>
      <?php echo $block->getChildHtml('xpc_settings_payment_method_title'); ?>
      <?php echo $block->getChildHtml('xpc_settings_payment_method_init_action'); ?>
      <?php echo $block->getChildHtml('xpc_settings_payment_method_allow_specific'); ?>
      <?php echo $block->getChildHtml('xpc_settings_payment_method_specific_country'); ?>

    </fieldset>
  </div>
</form>
