<?php
// vim: set ts=4 sw=4 sts=4 et:
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/license/OSL-3.0
 *
 * @author     X-Cart Holdings LLC <info@x-cart.com>
 * @category   CDev
 * @package    CDev_XPaymentsConnector
 * @copyright  (c) 2010-present X-Cart Holdings LLC <info@x-cart.com>. All rights reserved
 * @license    https://opensource.org/license/OSL-3.0  Open Software License (OSL 3.0)
 */
?>
<?php
/**
 * @see CDev\XPaymentsConnector\Block\Adminhtml\Settings\Tab\Welcome
 */
?>

<div class="payment-description">

  <div class="payment-logo">
    <img src="<?php echo $block->escapeUrl($block->getImageUrl('xpc-logo.png')); ?>" alt="X-Payments Connector"/>
  </div>

  <div class="description-block">
    <?php echo $block->escapeHtml($block->getDescription()); ?>
  </div>

  <div class="pci-logo"></div>

</div>

<h3 class="connect-caption">
  <?php echo $block->escapeHtml(__('Connect to X-Payments. Complete 3 easy steps.')); ?>
</h3>

<div class="payment-step">

  <div class="step">
    <span class="step-number">1</span>
    <p>
      <?php echo $block->escapeHtml(__('Open your X-Payments dashboard or')); ?>
    </p>
    <button onclick="javascript: window.open('<?php /* @noEscape */ echo $block->escapeJs($block->escapeUrl($block->getTrialDemoUrl())); ?>');">
      <?php echo $block->escapeHtml(__('Start FREE Trial')); ?>
    </button>
  </div>

  <img src="<?php echo $block->escapeUrl($block->getImageUrl('step-arrow.png')); ?>" class="step-arrow" />

  <div class="step">
    <span class="step-number">2</span>
    <p>
      <?php echo $block->escapeHtml(__('Configure your gateway in')); ?>
      <strong style="white-space: nowrap;"><?php echo $block->escapeHtml(__('X-Payments')); ?></strong>
    </p>
    <a href="<?php echo $block->escapeUrl($block->getUserManualGatewaysUrl()); ?>" target="_blank"><?php echo $block->escapeHtml(__('See how')); ?></a>
  </div>

  <img src="<?php echo $block->escapeUrl($block->getImageUrl('step-arrow.png')); ?>" class="step-arrow" />

  <div class="step">
    <span class="step-number">3</span>
    <p>
      <a href="javascript: goToTab('connection');" id="connect-link" title="<?php echo $block->escapeHtmlAttr(__('Go to Connection settings tab')); ?>">
        <?php echo $block->escapeHtml(__('Connect')); ?>
        <strong><?php echo $block->escapeHtml(__('X-Payments')); ?></strong>
        <?php echo $block->escapeHtml(__('with')); ?>
        <strong><?php echo $block->escapeHtml(__('Magento')); ?></strong>
      </a>
    </p>
    <a href="<?php echo $block->escapeUrl($block->getUserManualMagentoUrl()); ?>" target="_blank"><?php echo $block->escapeHtml(__('See how')); ?></a>
  </div>

</div>
