<?php
// vim: set ts=4 sw=4 sts=4 et:
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/license/OSL-3.0
 *
 * @author     X-Cart Holdings LLC <info@x-cart.com>
 * @category   CDev
 * @package    CDev_XPaymentsConnector
 * @copyright  (c) 2010-present X-Cart Holdings LLC <info@x-cart.com>. All rights reserved
 * @license    https://opensource.org/license/OSL-3.0  Open Software License (OSL 3.0)
 */
?>
<?php
/**
 * @see CDev\XPaymentsConnector\Block\Adminhtml\Settings\Tab\ZeroAuth
 */
?>

<div class="fieldset-wrapper-title">
  <strong class="title"><?php echo $block->escapeHtml(__('Payment Card setup')); ?></strong>
</div>

<p class="admin__field-control">
  <?php echo __('Configure saving their credit or debit cards by customers in their user profiles.'); ?>
</p>

<form action="<?php echo $block->escapeUrl($block->getUrl('xpc/settings/zeroauth')); ?>" method="post" name="update_form" id="zero-auth-form">
  <?php echo $block->getBlockHtml('formkey'); ?>
  <input type="hidden" name="store" value="<?php echo $block->getCurrentStoreId(); ?>" />
  <input type="hidden" name="mode" value="update" id="zero-auth-form-mode" />

  <div class="fieldset-wrapper">
    <fieldset class="admin__fieldset">

      <?php echo $block->getChildHtml('xpc_settings_zero_auth_enabled'); ?>
      <?php echo $block->getChildHtml('xpc_settings_zero_auth_amount'); ?>
      <?php echo $block->getChildHtml('xpc_settings_zero_auth_description'); ?>

    </fieldset>
  </div>

</form>
