<?php
// vim: set ts=2 sw=2 sts=2 et:
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @author     Qualiteam Software <info@x-cart.com>
 * @category   CDev
 * @package    CDev_XPaymentsConnector
 * @copyright  (c) 2010-present Qualiteam software Ltd <info@x-cart.com>. All rights reserved
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
/**
 * @see CDev\XPaymentsConnector\Block\PaymentCard\Grid
 */
?>
<?php if ($block->hasPaymentCards()): ?>

  <div class="table-wrapper saved-payment-cards">
    <table class="data table table-payment-cards" id="my-payment-cards-table">
      <caption class="table-caption"><?= /* @noEscape */ __('Saved Payment Cards') ?></caption>
      <thead>
        <tr>
          <th scope="col" class="col card-number"><?= /* @noEscape */ __('Card Number') ?></th>
          <th scope="col" class="col actions">&nbsp;</th>
        </tr>
      </thead>
      <tbody>
        <?php foreach ($block->getPaymentCards() as $card): ?>
          <tr>
            <td>
              <span class="xpc-card-logo-list <?php echo $card['type']; ?>"></span>
              <?php echo $card['label'] ?>
            </td>
            <td class="col actions">
              <a href="<?php echo $card['delete_url']; ?>" class="action delete"><?php echo __('Delete'); ?></a>
            </td>
          </tr>
        <?php endforeach; ?>
      </tbody>
    </table>
  </div>

<?php else: ?>

    <div class="message info empty">
      <span><?= /* @noEscape */ __('No saved payment cards.') ?></span>
    </div>

<?php endif ?>

<a href="<?php echo $block->getAddPaymentCardLink(); ?>" class="action primary"><?php echo __('Add New Payment Card'); ?></a>
