<?php
// vim: set ts=2 sw=2 sts=2 et:
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @author     Qualiteam Software <info@x-cart.com>
 * @category   CDev
 * @package    CDev_XPaymentsConnector
 * @copyright  (c) 2010-present Qualiteam software Ltd <info@x-cart.com>. All rights reserved
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
/**
 * @see CDev\XPaymentsConnector\Block\Adminhtml\Settings\Field\Select
 */
?>
<div class="admin__field">
  <label class="admin__field-label">
    <span><?php echo $block->escapeHtml(__($block->getFieldTitle())); ?></span>
  </label>
  <div class="admin__field-control">
    <select name="<?php echo $block->escapeHtmlAttr($block->getFieldName()); ?>"
            id="<?php echo $block->escapeHtmlAttr($block->getNameInLayout()); ?>"
            <?php if ($block->getIsMultiple()): ?>multiple="multiple" size="10" class="select multiselect admin__control-multiselect"<?php else: ?>class="select admin__control-select"<?php endif; ?>
            <?php if ($block->getIsDisabled()): ?>disabled="disabled"<?php endif; ?>
            <?php if ($block->getOnChange()): ?>onchange="javascript: <?php echo $block->escapeHtmlAttr($block->getOnChange()); ?>"<?php endif; ?>
    >
      <?php foreach ($block->getFieldOptions() as $value => $title): ?>
        <option value="<?php echo $block->escapeHtmlAttr($value); ?>" <?php if ($block->isSelected($value)): ?>selected="selected"<?php endif; ?>>
          <?php echo $block->escapeHtml(__($title)); ?>
        </option>
      <?php endforeach; ?>
    </select>
    <?php if ($block->getComment()): ?>
      <p class="note"><?php echo $block->escapeHtml(__($block->getComment())); ?></p>
    <?php endif; ?>
  </div>
</div>
