<?php
// vim: set ts=2 sw=2 sts=2 et:
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/license/OSL-3.0
 *
 * @author     X-Cart Holdings LLC <info@x-cart.com>
 * @category   CDev
 * @package    CDev_XPaymentsConnector
 * @copyright  (c) 2010-present X-Cart Holdings LLC <info@x-cart.com>. All rights reserved
 * @license    https://opensource.org/license/OSL-3.0  Open Software License (OSL 3.0)
 */
?>
<?php
/**
 * @see CDev\XPaymentsConnector\Block\Processing\Redirect
 */
?>

<form action="<?php echo $block->getFormAction(); ?>" method="post" id="xpc-form-redirect">
  <input type="hidden" name="action" value="start"/>
  <input type="hidden" name="allow_save_card" value="<?php echo $block->getAllowSaveCard(); ?>"/>
  <input type="hidden" name="token" value="<?php echo $block->getPaymentToken(); ?>"/>
</form>

<script type="text/javascript">
//<![CDATA[
  var paymentform = document.getElementById('xpc-form-redirect');
  window.onload = function() {
    paymentform.submit();
  }
//]]>
</script>
