<?php
// vim: set ts=2 sw=2 sts=2 et:
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/license/OSL-3.0
 *
 * @author     X-Cart Holdings LLC <info@x-cart.com>
 * @category   CDev
 * @package    CDev_XPaymentsConnector
 * @copyright  (c) 2010-present X-Cart Holdings LLC <info@x-cart.com>. All rights reserved
 * @license    https://opensource.org/license/OSL-3.0  Open Software License (OSL 3.0)
 */
?>
<?php
/**
 * @see CDev\XPaymentsConnector\Block\Adminhtml\PaymentCard\Add
 */
?>

<div class="add-new-card-container">

  <iframe class="xpc-iframe" id="xpc-iframe" src="<?php echo $block->getIframeUrl(); ?>"></iframe>

  <div class="xpc-address">
    <address>
      <strong><?php echo __('Billing Address'); ?></strong>
      <br/>
      <?php echo $block->getAddressHtml(); ?>
    </address>
  </div>

</div>
