<?php
// vim: set ts=2 sw=2 sts=2 et:
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/license/OSL-3.0
 *
 * @author     X-Cart Holdings LLC <info@x-cart.com>
 * @category   CDev
 * @package    CDev_XPaymentsConnector
 * @copyright  (c) 2010-present X-Cart Holdings LLC <info@x-cart.com>. All rights reserved
 * @license    https://opensource.org/license/OSL-3.0  Open Software License (OSL 3.0)
 */
?>
<?php
/**
 * @see CDev\XPaymentsConnector\Block\Adminhtml\PaymentCard\CardList
 */
?>

<fieldset class="admin__fieldset payment-method" id="payment_form_<?= /* @noEscape */ $block->getMethodCode(); ?>" style="display: none;">

  <div class="admin__field">
    <ul class="xpc-payment-cards admin__field-control">
      <?php foreach ($block->getPaymentCards() as $card): ?>

        <li>
          <input 
              type="radio" 
              name="payment[card_id]" 
              value="<?= /* @noEscape */ $card['card_id']; ?>" 
              id="xpc-card-'<?= $card['card_id']; ?>" 
              class="radio required-entry"
              data-validate="{'validate-one-required-by-name':true}"
              />
          <label class="label" for="xpc-card-'<?= $card['card_id']; ?>">
            <span class="xpc-card-logo xpc-card <?= $card['type']; ?>"></span>
            <span class="cc-number"><?= $card['label']; ?></span>
          </label>
        </li>

      <?php endforeach; ?>
    </ul>
  </div>

</fieldset>
